# Generated by Django 2.1.4 on 2019-05-15 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20190515_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 15, 34, 30, 982464)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 15, 34, 30, 982464)),
        ),
    ]
